(define (equal? a b)
  (cond ((and (null? a) (null? b)) #t)
        ((and (pair? a) (not (pair? b))) #f)
        ((and (pair? b) (not (pair? a))) #f)
        ((not (or (pair? a) (pair? b))) (eq? a b))
        (else (and (equal? (car a) (car b)) (equal? (cdr a) (cdr b))))))
