(define (cont-frac n d k)
  (define (iter count result)
    (let ((x result))
       (if (= count 1)
           result
           (iter (- count 1) (/ (n (- count 1)) (+ (d (- count 1)) x))))))
  (iter k (/ (n k) (d k))))

(define (approx-e k)
  (define (n i) 1.0)
  (define (d i)
     (if (= (remainder i 3) 2)
         (+ 2 (* 2 (/ (- i 2) 3)))
         1.0))
  (+ 2 (cont-frac n d k)))